security:
    providers:
        database_users:
            entity:
                class: App\Users\User
                property: username

        in_memory:
            memory:
                users:
                    ahmvTQLrm3Lw:
                        password: "%env(API_KEY)%"
                        roles: 'ROLE_API'

    encoders:
        App\Users\User:
            algorithm: bcrypt
            cost: 12
        Symfony\Component\Security\Core\User\User: plaintext


    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        api:
            pattern: ^/api/
            stateless: true
            http_basic: ~
            provider: in_memory

        main:
            anonymous: ~
            logout:
                path:   /logout
                target: /login
            guard:
                authenticators:
                    - App\Security\LoginFormAuthenticator
            provider: database_users

    access_control:
        - { path: ^/users/request-password-reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users/password-sent, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/users/password-reset, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, roles: ROLE_API }
        - { path: ^/, roles: [ROLE_ADMIN, ROLE_CUSTOMER_SUPPORT] }
