App\Users\User:
    type: entity
    table: users
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        username:
            type: string
            unique: true
        password:
            type: string
        roles:
            type: string
        active:
            type: boolean
            default: 1
        resetToken:
            type: string
            length: 32
            nullable: true
        resetExpiresAt:
            type: integer
            nullable: true

    lifecycleCallbacks: {  }
